/*
 * Here to Help
 * This is a restful web service used to log hours for non-profits to submit for money grants.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.dsmhack.model;

import com.google.gson.Gson;

import javax.persistence.*;
import java.sql.Timestamp;

@Entity
@Table
public class CheckIn {

    @Id
    @Column
    private String userGuid;

    @Column
    private String projGuid;

    @Column
    private Timestamp timeIn;

    @Column
    private Timestamp timeOut;

    public CheckIn(){}

    public String getUserGuid() {
        return userGuid;
    }

    public CheckIn setUserGuid(String userGuid) {
        this.userGuid = userGuid;
        return this;
    }

    public String getProjGuid() {
        return projGuid;
    }

    public CheckIn setProjGuid(String projGuid) {
        this.projGuid = projGuid;
        return this;
    }

    public Timestamp getTimeIn() {
        return timeIn;
    }

    public CheckIn setTimeIn(Timestamp timeIn) {
        this.timeIn = timeIn;
        return this;
    }

    public Timestamp getTimeOut() {
        return timeOut;
    }

    public CheckIn setTimeOut(Timestamp timeOut) {
        this.timeOut = timeOut;
        return this;
    }

    public String toJson() {
        return new Gson().toJson(this);
    }
}

