/*
 * Here to Help
 * This is a restful web service used to log hours for non-profits to submit for money grants.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.dsmhack.model;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Timestamp;

/**
 * LoginToken
 */
@Entity
@Table(name = "LOGIN_TOKEN")
public class LoginToken {
    @EmbeddedId
    private MyKey myKey;

    public MyKey getMyKey() {
        return myKey;
    }

    public void setMyKey(MyKey myKey) {
        this.myKey = myKey;
    }

    @Embeddable
    public class MyKey implements Serializable {

        @Column(name = "USER_GUID", nullable = false)
        private String userGuid;

        @Column(name = "TOKEN", nullable = false)
        private String token;

        @Column(name = "TOKEN_EXP_DATE", nullable = false)
        private Timestamp tokenExpDate;

        public String getUserGuid() {
            return userGuid;
        }

        public void setUserGuid(String userGuid) {
            this.userGuid = userGuid;
        }

        public String getToken() {
            return token;
        }

        public void setToken(String token) {
            this.token = token;
        }

        public Timestamp getTokenExpDate() {
            return tokenExpDate;
        }

        public void setTokenExpDate(Timestamp tokenExpDate) {
            this.tokenExpDate = tokenExpDate;
        }
    }
}

