/*
 * Here to Help
 * This is a restful web service used to log hours for non-profits to submit for money grants.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.dsmhack.model;

import com.google.gson.Gson;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table
public class Project {
    @Id
    @Column
    private String projGuid;

    @NotNull
    @Size(min = 1, max = 36)
    @Column
    private String orgGuid;

    @NotNull
    @Size(min = 1, max = 50)
    @Column
    private String name;

    @NotNull
    @Size(min = 1, max = 50)
    @Column
    private String description;

    @Column
    private LocalDateTime startDate;

    @Column
    private LocalDateTime endDate;

    public Project() {
    }

    public String getProjGuid() {
        return projGuid;
    }

    public Project setProjGuid(String projGuid) {
        this.projGuid = projGuid;
        return this;
    }

    public String getOrgGuid() {
        return orgGuid;
    }

    public Project setOrgGuid(String orgGuid) {
        this.orgGuid = orgGuid;
        return this;
    }

    public String getName() {
        return name;
    }

    public Project setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public Project setDescription(String description) {
        this.description = description;
        return this;
    }

    public LocalDateTime getStartDate() {
        return startDate;
    }

    public Project setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
        return this;
    }

    public LocalDateTime getEndDate() {
        return endDate;
    }

    public Project setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
        return this;
    }

    public String toJson() {
        return new Gson().toJson(this);
    }
}

