/*
 * Here to Help
 * This is a restful web service used to log hours for non-profits to submit for money grants.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.dsmhack.model;

import com.google.gson.Gson;

import javax.persistence.*;
import java.io.Serializable;
import java.util.UUID;

@Entity
@Table
public class UserProject {
    @EmbeddedId
    private MyKey myKey;

    public MyKey getMyKey() {
        return myKey;
    }

    public void setMyKey(MyKey myKey) {
        this.myKey = myKey;
    }

    @Embeddable
    public static class MyKey implements Serializable {
        @Column
        private UUID userGuid;

        @Column
        private UUID projectGuid;

        public UUID getUserGuid() {
            return userGuid;
        }

        public void setUserGuid(UUID userGuid) {
            this.userGuid = userGuid;
        }

        public UUID getProjectGuid() {
            return projectGuid;
        }

        public void setProjectGuid(UUID projectGuid) {
            this.projectGuid = projectGuid;
        }
    }

    public String toJson() {
        return new Gson().toJson(this);
    }
}

