create table organization (
ORG_GUID CHAR(36) NOT NULL,
NAME VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(250) NOT NULL,
PHONE VARCHAR(10) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
WEB_URL VARCHAR(50) NOT NULL,
FACEBOOK VARCHAR(50) NOT NULL,
TWITTER VARCHAR(50) NOT NULL,
INSTAGRAM VARCHAR(50) NOT NULL,
PRIMARY KEY (ORG_GUID));
